name: Code Checker
run-name: Running Code Checker for ${{ github.ref }} on ${{ github.event_name }} 🔎

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run linter
        run: uv run ruff check .

  check-formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync

      - name: Run formatter
        run: uv run ruff format --check .

  check-type-safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync

      - name: Run pyright
        run: uv run pyright

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync

      - name: Run pytest
        run: uv run pytest